version: "3"

services:
  weatwork:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
     - ./weatwork:/weatwork
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"



