version: "3"

services:
  weatwork:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
     - ./weatwork:/weatwork
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=weatwork
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
    depends_on:
      - db
  

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=weatwork
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD



