# Generated by Django 3.2.7 on 2021-10-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20211007_1314"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_company_owner",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_notice_period",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_open_to_work",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_self_employed",
            field=models.BooleanField(null=True),
        ),
    ]
