# Generated by Django 3.2.7 on 2021-10-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211013_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(max_length=100)),
                ('headquarters_country', models.CharField(max_length=200)),
                ('headquarters_address', models.CharField(max_length=200)),
                ('headquarters_zip_code', models.CharField(max_length=200)),
                ('motto', models.CharField(max_length=255)),
                ('decription', models.CharField(max_length=255)),
                ('logo_url', models.CharField(default='https://cdn.pixabay.com/photo/2019/07/26/20/52/man-4365597_960_720.png', max_length=500)),
                ('number_of_employees', models.IntegerField()),
                ('creation_date', models.DateField(null=True)),
            ],
        ),
    ]
