# Generated by Django 3.2.7 on 2021-10-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.IntegerField(default=0),
        ),
    ]
