# Generated by Django 3.2.7 on 2021-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211020_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('media_type', models.CharField(max_length=100)),
                ('gallery_name', models.CharField(max_length=255)),
                ('gallery_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('path', models.URLField(blank=True, max_length=255)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('language', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='type',
        ),
    ]
