# Generated by Django 3.2.7 on 2021-10-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211021_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='type',
            new_name='name',
        ),
    ]
