# Generated by Django 3.2.7 on 2021-10-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='user',
            new_name='author',
        ),
    ]
