# Generated by Django 3.2.7 on 2021-10-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_user_tag_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='path',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
