# Generated by Django 3.2.7 on 2021-10-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20211024_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorite_type',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='text',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='decription',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='text',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
