# Generated by Django 3.2.7 on 2021-10-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20211024_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='https://cdn.pixabay.com/photo/2019/07/26/20/52/man-4365597_960_720.png', upload_to=''),
        ),
    ]
