# Generated by Django 3.2.7 on 2021-10-29 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='gallery_name',
        ),
        migrations.RemoveField(
            model_name='media',
            name='gallery_type',
        ),
        migrations.AddField(
            model_name='media',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gallery'),
        ),
    ]
