# Generated by Django 3.2.7 on 2021-10-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mood',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
