# Generated by Django 3.2.7 on 2021-10-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_mediatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatype',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
