# Generated by Django 3.2.7 on 2021-11-07 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20211107_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
