# Generated by Django 3.2.7 on 2021-11-07 21:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='favorite',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='media',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='mediatype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='profiletype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
