# Generated by Django 3.2.7 on 2021-11-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20211107_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='media_type',
        ),
    ]
