# Generated by Django 3.2.7 on 2021-11-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_media_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediatype'),
        ),
    ]
