# Generated by Django 3.2.7 on 2021-11-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_mediatype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='motto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
