# Generated by Django 3.2.7 on 2021-11-08 13:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_user_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=core.models.uuid_generator, editable=False),
        ),
    ]
