# Generated by Django 3.2.7 on 2021-11-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='male-worker-default.jpg', upload_to=''),
        ),
    ]
